services:
  - type: web
    name: github-actions-status
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    regions:
      - oregon
    envVars:
      - key: GITHUB_API_TOKEN
        value: ${GITHUB_API_TOKEN}
      - key: GITHUB_REPO
        value: ${GITHUB_REPO}
      - key: WORKFLOW_FILE_NAME
        value: ${WORKFLOW_FILE_NAME}