name: Windows 11

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ngrok
        run: |
          # Unduh file ngrok.zip yang sesuai untuk Windows
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          
          # Ekstrak file zip yang diunduh
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok

          # Pindahkan ngrok.exe ke direktori yang dapat diakses (misalnya C:\Windows\System32)
          Move-Item -Path ngrok\ngrok.exe -Destination C:\Windows\System32
          
          # Hapus file zip dan folder ekstrak setelah selesai
          Remove-Item -Path ngrok.zip
          Remove-Item -Path ngrok -Recurse

      - name: Set ngrok auth token from secrets
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "Ngrok auth token set successfully"
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Run start.bat to setup RDP and ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          start /b cmd /c start.bat
          
      - name: Display RDP login info
        run: |
          timeout /t 10
          curl -s http://127.0.0.1:4040/api/tunnels | findstr "tcp://"
          echo "=================================="
          echo "RDP LOGIN DETAILS"
          echo "=================================="
          echo "Username: Administrator"
          echo "Password: HenCoders"
          echo "Port : 3389"
          echo "=================================="
