name: Windows 11 RDP Setup

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        timeout-minutes: 10

      - name: Install ngrok
        run: |
          echo "Downloading ngrok..."
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok
          Move-Item -Path ngrok\ngrok.exe -Destination C:\Windows\System32
          Remove-Item -Path ngrok.zip
          Remove-Item -Path ngrok -Recurse
        timeout-minutes: 15

      - name: Set ngrok auth token from secrets
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        timeout-minutes: 5

      - name: Verify start.bat exists and print directory
        run: |
          echo "Current directory:"
          dir  # Menampilkan direktori kerja saat ini untuk memastikan start.bat berada di sana
          echo "Checking if start.bat exists..."
          if (Test-Path -Path '../../start.bat') {
            echo "start.bat exists."
          } else {
            echo "start.bat does not exist in the current directory."
            exit 1  # Keluar jika start.bat tidak ditemukan
          }
        timeout-minutes: 5

      - name: Run start.bat to initialize RDP and ngrok
        run: |
          cmd.exe /c ../../start.bat  # Menjalankan start.bat dari root directory
        timeout-minutes: 30

      - name: Wait for ngrok tunnel to start
        run: |
          echo "Waiting for ngrok to start..."
          Start-Sleep -Seconds 60  # Waiting 60 seconds to ensure ngrok is up and running
        timeout-minutes: 5

      - name: Verify ngrok status and display login info
        run: |
          $tunnel_info = curl -s http://127.0.0.1:4040/api/tunnels | ConvertFrom-Json
          
          if ($tunnel_info.tunnels -ne $null -and $tunnel_info.tunnels.Count -gt 0) {
            $rdp_url = $tunnel_info.tunnels[0].public_url
            echo "Ngrok Tunnel: $rdp_url"
            echo "=================================="
            echo "RDP LOGIN DETAILS"
            echo "=================================="
            echo "Username: Administrator"
            echo "Password: HenCoders"
            echo "Port: 3389"
            echo "=================================="
          } else {
            echo "Ngrok tunnel not found. Please check ngrok status."
            exit 1  # Exit with error if no tunnel found
          }
        timeout-minutes: 5
