name: Windows 11

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        timeout-minutes: 10

      - name: Install ngrok
        run: |
          echo "Downloading ngrok..."
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok
          Move-Item -Path ngrok\ngrok.exe -Destination C:\Windows\System32
          Remove-Item -Path ngrok.zip
          Remove-Item -Path ngrok -Recurse
        timeout-minutes: 15

      - name: Set ngrok auth token from secrets
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        timeout-minutes: 5

      - name: Run start.bat to initialize RDP and ngrok
        run: |
          cmd.exe /c start.bat
        timeout-minutes: 30

      - name: Wait for ngrok tunnel to start
        run: |
          echo "Waiting for ngrok to start..."
          Start-Sleep -Seconds 20  # Menunggu 20 detik agar ngrok siap
        timeout-minutes: 5

      - name: Display RDP login info
        run: |
          echo "=================================="
          echo "RDP LOGIN DETAILS"
          echo "=================================="
          $tunnel_info = curl -s http://127.0.0.1:4040/api/tunnels | ConvertFrom-Json
          $rdp_url = $tunnel_info.tunnels[0].public_url
          echo "Ngrok Tunnel: $rdp_url"
          echo "Username: Administrator"
          echo "Password: HenCoders"
          echo "Port : 3389"
          echo "=================================="
        timeout-minutes: 5
