name: Windows 11

on:
  push:
    branches:
      - main

jobs:
  setup-rdp:
    runs-on: windows-latest  # Gunakan runner Windows yang terbaru

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        timeout-minutes: 10  # Timeout untuk checkout repository

      - name: Install ngrok
        run: |
          echo "Downloading ngrok..."
          Invoke-WebRequest -Uri https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive -Path ngrok.zip -DestinationPath ngrok
          Move-Item -Path ngrok\ngrok.exe -Destination C:\Windows\System32
          Remove-Item -Path ngrok.zip
          Remove-Item -Path ngrok -Recurse
        timeout-minutes: 15  # Timeout untuk instalasi ngrok

      - name: Set ngrok auth token from secrets
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}  # Gunakan secret ngrok untuk keamanan
        run: |
          echo "Ngrok auth token set successfully"
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        timeout-minutes: 5  # Timeout untuk konfigurasi ngrok

      - name: Run start.bat to setup RDP and ngrok
        run: |
          echo "Running start.bat to initialize RDP and Ngrok..."
          cmd.exe /c start.bat  # Memanggil start.bat menggunakan cmd.exe di PowerShell
        timeout-minutes: 30  # Timeout untuk menjalankan start.bat

      - name: Display RDP login info
        run: |
          echo "=================================="
          echo "RDP LOGIN DETAILS"
          echo "=================================="
          curl -s http://127.0.0.1:4040/api/tunnels | findstr "tcp://"
          echo "Username: Administrator"
          echo "Password: HenCoders"
          echo "Port : 3389"
          echo "=================================="
        timeout-minutes: 5  # Timeout untuk menampilkan informasi RDP
